CHANGELOG.md, pbs.py, qtop.py
yaml is now used for dumping and loading, except for the creation of pbsnodes yaml.
Maybe we should consider keeping the python writers, they are faster.
Also, the rewrites eliminating some if elif structures are actually SLOWER!!
=> New refactor branch

pbs.py, qtop.py
yaml (via both pyyaml and manual yaml) and json parsing work seamlessly
=> New refactor wave

colormap.py, common_module.py, plugin_oar.py, plugin_pbs.py, plugin_sge.py, qtop.py, qtopconf.yaml, stat_maker.py
=> chore: python2.6 compatibility support

common_module.py, plugin_pbs.py, qtop.py, qtopconf.yaml, yaml_parser.py
various minor features (don't let the title full you!)
=> ch-refactoring-fixes

common_module.py, qtop.py, qtopconf.yaml
=> get_gecos_via_getent_passwd implemented

common_module.py, plugin_pbs.py, qtop.py, serialiser.py, yaml_parser.py
(will run with anything that it can get)
=> still runs for empty PBS systems (about to be populated)

qtop.py, ui/viewport.py
Adding vagrant support for a Torque/PBS system
=> Extracting a viewport class

qtop.py, ui/viewport.py
merging lookfwd's Viewport with some minor fixes
=> Viewport test

common_module.py, qtop.py, qtopconf.yaml, tests/ui/test_viewport.py, ui/viewport.py, yaml_parser.py
really experimental, mostly just for code review and critique!! @lookfwd @fgeorgatos
=> Refactor into new TextDisplay class

plugins/demo.py
=> A more realistic demo

common_module.py, plugins/sge.py, qtop.py, qtopconf.yaml, tests/test_qtop.py, tests/test_yaml_parser.py
fixed issue [101](https://github.com/qtop/qtop/issues/101)
=> removed hardwired mentions of sge/pbs/oar (except for comments)

utils.py
until input files are excluded from tarball or are also anonymised
=> temporarily disable anonymise

plugins/pbs.py, qtopconf.yaml, serialiser.py
qtop also exits more gracefully (and descriptively) when qstat lines are not matched
=> added a new job state ('H')

plugins/pbs.py, qtop.py
=> array job ids supported

plugins/sge.py
also changed a variable name for better readability
=> fixed bug where some jobs would not be displayed in the matrix

plugins/pbs.py, qtop.py, qtopconf.yaml
new format: <job_id_nr[fragment]>
qtop disregards this, as it doesn't seem to bring any valuable info
=> support for new jobid format in PBS

qtop.py
fixing https://github.com/qtop/qtop/issues/212
=> screen should only clear in watch mode

qtop.py
fix for https://github.com/qtop/qtop/issues/262
=> handle non-availability of getent in some machines

README.rst, qtop.py, qtop_py/colormap.py, qtop_py/contrib/qstat.F.xml.stdout, qtop_py/fileutils.py, qtop_py/plugins/pbs.py, qtop_py/plugins/sge.py, qtop_py/serialiser.py, qtop_py/utils.py
anonymize for SGE back in the game.
performance improvements for SGE
=> fix-anonymize-SGE-and-optimisations

qtop_py/plugins/pbs.py
'@' is a valid symbol in job names, added to regex.
=> Add valid character to PBS regex

qtop.py
This is to address issue #64 by refactoring so shell=True can be removed.
Lists of the command and it's arguments are passed to subprocess functions., this keeps other processes from being injected. pipelines done in the command have been pulled out into subprocess.pipeline. Fully qualified paths are being added to shell commands as well.
=> subprocess security concerns

CONTRIBUTING.md, CONTRIBUTING.rst
Either DCO or CLA are acceptable.
Be more welcoming to different types of contributions and provide guidelines and pointers.
=> docs: Update and rename CONTRIBUTING.rst to CONTRIBUTING.md
